#!/usr/bin/env bash
# Runs the unit/integration suite (`bal test`) against a throwaway SQLite database.
#
# Nothing here touches .env: the tests must not depend on a developer's real OpenAI key or
# write to the database the agent serves from. The encryption key below is a fixed test
# fixture — tests/fernet_test.bal contains Fernet tokens generated by Python under this exact
# key, which is what verifies the Ballerina implementation is wire-compatible rather than
# merely self-consistent.
#
# Usage: ./test.sh                       # whole suite
#        ./test.sh --groups fernet       # one group: fernet | policy | store | observability
#                                        #   | scope | identity | encryption | interop

set -euo pipefail
cd "$(dirname "$0")"

if [ -z "${JAVA_HOME:-}" ] && command -v brew >/dev/null 2>&1; then
    export JAVA_HOME="$(brew --prefix openjdk)"
fi

export CASEMGMT_ENCRYPTION_KEY="V1KMEbNn7hbwsUyoIWzk3fRlZeMxaBLGyQCbdWLmYnE="
export CASEMGMT_DB_PATH="target/test-data/case_mgmt_test.db"
export CASEMGMT_SEED_DIR="seed"
export CASEMGMT_SEED_ON_START="true"
export COUNTY_NAME="Riverside County"
# Deliberately empty: no test should reach the LLM, and an accidental live call would show up
# as an auth failure rather than a surprise bill.
export OPENAI_API_KEY=""

# Fresh database each run, so a leftover row can't make a test pass (or fail) on its own.
rm -rf target/test-data
mkdir -p target/test-data

exec bal test "$@"
